apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql-app             # matches the label used in the template

  template:
    metadata:
      labels:
        app: mysql-app           # no convention for these - but they must match
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name:  MYSQL_DATABASE        # database to create automatically
              value: QUOTES
            - name: "MYSQL_ROOT_PASSWORD"
              value: "root"
          volumeMounts:
            - name: mysql-vol
              mountPath: /var/lib/mysql
              subPath: mysql
      volumes:
      - name: mysql-vol              # attach to our persistent storage
        persistentVolumeClaim:
          claimName: mysql-storage-claim
