db:
  image: mysql:5.7
  container_name: db
  environment:
      MYSQL_ROOT_PASSWORD: root
# redis:
#   image: redis:latest
#   container_name: redis
app:
  build: ./app
  ports:
   - "5000:5000"
  links:
   # - redis:redis
   - db:db
