apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: quoteapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quoteapp
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: messages
      targetAverageValue: 30
