apiVersion: v1
kind: Service
metadata:
  name: quoteapp-svc
  labels:
    name: quoteapp
    app: quoteapp
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
  selector:
    app: quoteapp
