apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-claim
spec:
  storageClassName: oci
  selector:
    matchLabels:
      failure-domain.beta.kubernetes.io/zone: "AD-1"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
